### ISSUE TITLE
Error storing test results in BigQuery - 'str' object has no attribute 'database'

### ISSUE THREAD

**Issue by matthh9797jetty** [infinitelambda/dq-tools#33]
### Describe the bug

When setting up the package exactly as described in the README for version ">=1.4.0", "<1.5.0" in BigQuery, DBT version v1.8. The following error appears when trying to run tests with the variable `dq_tools_enable_store_test_results` set to `true`. 

```
File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/adapters/bigquery/impl.py", line 244, in get_columns_in_relation
    database=relation.database, schema=relation.schema, identifier=relation.identifier

AttributeError: 'str' object has no attribute 'database'
```

### Steps to reproduce

Setup a DBT v1.8 project in Bigquery and run the setup instructions as specified in the README:

- Add to `packages.yml` file:

  ```yml
  packages:
    - package: infinitelambda/dq_tools
      version: [">=1.4.0", "<1.5.0"]
  ```

- Configure schema in `dbt_project.yml` file:

  ```yml
  vars:
    # (optional) to create db table in the schema named as AUDIT, default to `target.schema` if not specified
    dbt_dq_tool_schema: AUDIT
  ```

- Add on-run-end hook:

  ```yml
  on-run-end:
    - '{{ dq_tools.store_test_results(results) }}'
  ```

- Initialize `dq-tools` (new in v1.4+)

  ```bash
  dbt run -s dq_tools 
  ```

Then run the following:

```bash
dbt test --vars '{dq_tools_enable_store_test_results: true}'
```

### Expected results

DBT test results to be stored in the `dq_issue_log` table in BigQuery.

### Actual results

DBT generates the following error:

```
Command failed
'str' object has no attribute 'database'
```

### Screenshots and log output

Error message in DBT Cloud:
![image](https://github.com/user-attachments/assets/2f2545ff-081a-4751-80cc-b42199cf389e)

Vars and post hook in `dbt_project.yml`:
![image](https://github.com/user-attachments/assets/578e1950-e616-4033-b51c-165d2b76018e)

Full Error output Local:
![image](https://github.com/user-attachments/assets/7c6e610e-1e83-4b30-be41-c8ca6833047c)
![image](https://github.com/user-attachments/assets/0e2df0b4-7945-47e5-84d5-ac0f88930e86)
![image](https://github.com/user-attachments/assets/f0a84cde-54d6-43cc-b84c-f5b465740255)

### System information

**The contents of your `packages.yml` file:**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: calogica/dbt_expectations
    version: 0.10.0
  - package: infinitelambda/dq_tools
    version: [">=1.4.0", "<1.5.0"]
```

**Which database are you using dbt with?**

- [x] bigquery
- [ ] snowflake

**The output of `dbt --version`:**

```log
dbt Cloud CLI - 0.38.15 (56359b0505efe701ed8992da750ca7058fe41806 2024-09-25T13:26:28Z)
```

### Additional context
The database attribute of `relation.database`  doesn't look to exist in BigQuery which is causing an error in the `get_columns_in_relation` function.

### Are you interested in contributing the fix?

I'll do what I can to provide context
